### PR TITLE
Modify more Database methods to support live updating

### PR DESCRIPTION
**Pull request by rpshukla**
This modifies the following Database methods to support live updating through the use of firebase snapshot listeners:
- `getUserById`
- `getExperimentsByOwner`
- `getExperimentsBySubscriber`
- `getExperimentsByTags`

It also updates the tests in Database test to pass with the new versions of these methods.

I have added tests called `testLiveUpdateExperiment` and `testSearchThenDelete` to test the live updating functionality.

### CODE REVIEW

**Comment by rpshukla** [comment]
I have not modified `getExperimentsByTags` to support live updating. That method will be trickier because there are multiple queries, each with its own `ListenerRegistration`.

There are 2 things we need to worry about:

1. `getExperimentsByTags` will probably have to return multiple `ListenerRegistration` instances and the caller will have to call `remove()` on each one. We could also create our own `ListenerRegistration` subclass that is composed of multiple instances.

2. There will be multiple snapshot listeners (one for each tag). Each individual snapshot listener may be updated a different number of times and out of order. For example, you could search for 2 tags. Then a new experiment is created that has only one of the tags. This will cause one snapshot listener to be called again.

**Comment by rpshukla** [comment]
Update: I have modified `getExperimentsByTags` to also support live updating. This fixes the issue where you could delete an experiment, be taken back to the search screen, and still see the experiment that was just deleted. In my implementation, I modified `getExperimentsByTags` to return a `LiveData`.

**Comment by rpshukla** [comment]
I just realized, this new version of `getExperimentsByTags` doesn't return the `ListenerRegistration`s returned by the multiple calls to `addSnapshotListener` so there is no way to call `remove()` on them. I will modify it to return them.

**Comment by rpshukla** [comment]
Update: now `getExperimentsByTags` returns a `ListenerRegistration`. I also removed the use of `LiveData` since I realized this was unnecessary.

**Review by vasu-gupta01 — APPROVED** [review]
These changes look good to me!

**Pull request merged**
