### PR TITLE
Make Database singleton

### PR DESCRIPTION
**Pull request by rpshukla**
This allows any activity or fragment to access the same Database instance.
This makes it easy to get information such as the device's ID.

- Create initializeInstance method to pass SharedPreferences to Database instance
- Call initializeInstance in MainActivity
- Move loadID and saveID methods from MainActivity to Database
  - rename loadID to initializeDeviceUser()
- Add Database method getDeviceUser() that gets the User instance associated with the device (i.e. has the correct id)

### CODE REVIEW

**Comment by Jacques857** [comment]
Thanks Ryan! Everything you did makes sense to me. However I think we should wait for @FurmaanS to review before merging since he was the one who mostly wrote loadID and saveID. So there might have been a reason that those were in the main activity other than being able to call them directly from the main activity for testing convenience.

**Comment by rpshukla** [comment]
This PR also changes the schema of the Users from this:

```
OwnedExperiments: ...
User: {
  id: ""
  email: ""
  ..
}
```

To this:
```
OwnedExperiments: ...
id: ""
email: ""
..
```

I found that this would make querying and re-constructing a User instance easier since you don't have to make another query to get the "User" field once you get the outer document.

If there is a reason we needed this additional "User" field let me know.

**Comment by Jacques857** [comment]
This shouldn't cause any problems with the existing Database methods. We will have to make a slight easy change to verifyId where we create a new user, but the only reason we stored the object rather than its fields in the first place was for convenience in coding. If we change the object to a few fields instead it won't cause problems.

**Comment by Jacques857** [comment]
@rpshukla Is there more to be done before this is ready for merging? It looks complete to me

**Comment by rpshukla** [comment]
> @rpshukla Is there more to be done before this is ready for merging? It looks complete to me

I think it's ready to merge.

**Pull request merged**
